GkCatalog\Domain\Domain\Entities\Catalog:
  type: entity
  repositoryClass: GkCatalog\Infrastructure\Persistence\Doctrine\Repositories\Domain\CatalogRepository
  table: domains
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update